name: NLP
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas>=2.3
  - scikit-learn>=1.7
  - gensim>=4.3
  - joblib>=1.5
  - nltk>=3.9
  - spacy>=3.7
  - sentence-transformers>=2.2
  - umap-learn>=0.5
  - pyspellchecker>=0.8
  - pip

  - pip:
      - bertopic>=0.17
      - hdbscan>=0.8
      - en-core-web-sm>=3.7
      - plotly>=6.2
